CREATE TABLE stg.Transactions_Raw (
    StageID BIGINT IDENTITY(1,1) PRIMARY KEY,
    BatchId UNIQUEIDENTIFIER NULL,
    SourceFileName NVARCHAR(500) NULL,
    Transaction_ID NVARCHAR(50) NOT NULL,
    Customer_ID NVARCHAR(50) NULL,
    Account_ID NVARCHAR(50) NULL,
    Transaction_Date DATE NULL,
    Transaction_Time TIME(0) NULL,
    Amount DECIMAL(18,2) NULL,
    Transaction_Type NVARCHAR(50) NULL,
    Merchant_Name NVARCHAR(200) NULL,
    Merchant_Category NVARCHAR(100) NULL,
    Merchant_City NVARCHAR(100) NULL,
    Merchant_State NVARCHAR(100) NULL,
    Merchant_Country NVARCHAR(100) NULL,
    Payment_Method NVARCHAR(50) NULL,
    Currency NVARCHAR(10) NULL,
    Device_Type NVARCHAR(50) NULL,
    Operating_System NVARCHAR(50) NULL,
    Transaction_Channel NVARCHAR(50) NULL,
    ATM_ID NVARCHAR(50) NULL,
    Branch_ID NVARCHAR(50) NULL,
    IFSC_Code NVARCHAR(20) NULL,
    Customer_Age INT NULL,
    Gender NVARCHAR(20) NULL,
    Occupation NVARCHAR(100) NULL,
    Income_Level NVARCHAR(50) NULL,
    Credit_Score INT NULL,
    Account_Type NVARCHAR(50) NULL,
    Balance_Before DECIMAL(18,2) NULL,
    Balance_After DECIMAL(18,2) NULL,
    Latitude DECIMAL(10,6) NULL,
    Longitude DECIMAL(10,6) NULL,
    IP_Address NVARCHAR(45) NULL,
    Login_Time DATETIME2 NULL,
    Logout_Time DATETIME2 NULL,
    Fraud_Label BIT NULL,
    Risk_Score INT NULL,
    Card_Type NVARCHAR(50) NULL,
    Card_Network NVARCHAR(50) NULL,
    Loan_Status NVARCHAR(50) NULL,
    Customer_Segment NVARCHAR(50) NULL,
    LoadUTC DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE UNIQUE NONCLUSTERED INDEX IX_stg_TransactionsRaw_TransactionID
ON stg.Transactions_Raw(Transaction_ID, LoadUTC DESC);
